backend:
  name: test-repo

media_folder: "src/assets/images"
public_folder: "src/assets/images"

collections:
  - label: "Home page"
    name: "homepage"
    files:
      - label: "Hero"
        name: "hero"
        file: "src/content/homepage/hero.md" # Path to the markdown file
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Background Image", name: "backgroundImage", widget: "image", required: false }
          - { label: "Button Text", name: "buttonText", widget: "string" }
